<?php
/**
 *  Return a list of vehicle manufacturers.
 *  Class contains individual methods for each type of vehicle.
 * 
 *  Use these methods to quickly pull an associative array of 
 *  vehicle manufacturers into your application.
 * 
 *  Current vehicles:
 *  Cars - cars()
 *  Motorcycles - motorcycles()
 * 
 *  @author Adam Terry <adam@advite.com.au>
 */
class Vehicles
{
    /**
     *  Return a list of Car manufacturers
     * 
     *  @author Adam Terry <adam@advite.com.au>
     *  @return array $carManufacturers
     */
    public function cars(){
         
        $cars = array(
            'ABARTH',
            'ABT',
            'AC',
            'ACURA',
            'AIXAM',
            'ALFA ROMEO',
            'ALPINA',
            'ALPINE',
            'ALVIS',
            'AMG',
            'ARASH',
            'ARIEL',
            'ARRINERA',
            'ARTEGA',
            'ASIA MOTORS',
            'ASTON MARTIN',
            'AUDI',
            'AUSTIN',
            'AUSTIN HEALEY',
            'AXON',
            'BAC',
            'BAIC',
            'BAOJUN',
            'BEDFORD',
            'BENTLEY',
            'BERTONE',
            'BHARATBENZ',
            'BITTER',
            'BMW',
            'BORGWARD',
            'BOWLER',
            'BRABUS',
            'BRAMMO',
            'BRILLIANCE',
            'BRISTOL',
            'BROOKE',
            'BUFORI',
            'BUGATTI',
            'BUICK',
            'BYD',
            'CADILLAC',
            'CAPARO',
            'CARLSSON',
            'CATERHAM',
            'CHANGAN',
            'CHANGFEN',
            'CHERY',
            'CHEVROLET',
            'CHRYSLER',
            'CITROEN',
            'CIZETA',
            'CORVETTE',
            'DACIA',
            'DAEWOO',
            'DAF',
            'DAIHATSU',
            'DAIMLER',
            'DARTZ',
            'DATSUN',
            'DAVID BROWN',
            'DE TOMASO',
            'DELOREAN',
            'DEVEL SIXTEEN',
            'DINA',
            'DMC',
            'DODGE',
            'DONGFENG',
            'DONKERVOORT',
            'DS AUTOMOBILES',
            'ELFIN',
            'EUNOS',
            'EXCALIBUR',
            'FERRARI',
            'FIAT',
            'FORD',
            'FPV',
            'GEELY',
            'GMC',
            'GOGGOMOBIL',
            'GREAT WALL',
            'HDT',
            'HILLMAN',
            'HINO',
            'HOLDEN',
            'HONDA',
            'HSV',
            'HUMMER',
            'HYUNDAI',
            'INFINITI',
            'INTERNATIONAL',
            'ISUZU',
            'IVECO',
            'JAGUAR',
            'JBA',
            'JEEP',
            'JENSEN',
            'KIA',
            'LAMBORGHINI',
            'LANCIA',
            'LAND ROVER',
            'LEXUS',
            'LEYLAND',
            'LINCOLN',
            'LOTUS',
            'MG',
            'MACK',
            'MAHINDRA',
            'MASERATI',
            'MAZDA',
            'MERCEDES',
            'MERCURY',
            'MINI',
            'MITSUBISHI',
            'MORGAN',
            'MORRIS',
            'NISSAN',
            'NISMO',
            'OLDSMOBILE',
            'PEUGEOT',
            'PLYMOUTH',
            'PONTIAC',
            'PORSCHE',
            'PROTON',
            'RAMBLER',
            'RENAULT',
            'ROLLS ROYCE',
            'ROVER',
            'SAAB',
            'SEAT',
            'SKODA',
            'SMART',
            'SSANGYONG',
            'STUDEBAKER',
            'SUBARU',
            'SUZUKI',
            'TESLA',
            'TOYOTA',
            'TRD',
            'TRIUMPH',
            'TVR',
            'UD',
            'ULTIMA',
            'VAUXHALL',
            'VOLKSWAGEN',
            'VOLVO',
            'WESTFIELD',
            'WILLYS',
            'WOLSELEY'
        );

        return $cars;
    }

    /**
     *  Return a list of Motorcycle manufacturers
     * 
     *  @author Adam Terry <adam@advite.com.au>
     *  @return array $motorcycleManufacturers
     */
    public function motorcycles(){

        $motorcycles = array(
            'ACABION',
            'ACE',
            'ADLER',
            'ADLY',
            'AEON',
            'AERMACCHI',
            'AJP',
            'AJS',
            'ALFER',
            'ALIGATOR',
            'AMAZONAS',            
            'AMC',
            'AMERICAN IRONHORSE',
            'ANZANI',
            'APRILIA',
            'ARCTIC CAT',
            'ARIEL',
            'ATK',
            'ATLAS HONDA',
            'ATOMO',
            'AUDI',
            'AUTOSTUDIO',
            'BAJAJ',
            'BATMAN',
            'BENNCHE',
            'BENELLI',
            'BETA',
            'BIG BEAR CHOPPERS',
            'BIMAN',
            'BIMOTA',
            'BLATA',
            'BLUE',
            'BMW',
            'BOMBARDIER RECREATIONAL PRODUCTS',
            'BORILE',
            'BOSS HOG CYCLES',
            'BRAMMO',
            'BRENNABOR',
            'BROUGH SUPERIOR',
            'BSA',
            'BUCCIMOTO',
            'BUELL',
            'BULTACO',
            'CAGIVA',
            'CAMPAGNA',
            'CAN-AM',
            'CANNONDALE',
            'CCM',
            'CENTAURUS',
            'CLEVELAND CYCLEWERKS',
            'CONDOR',
            'CONFEDERATE',
            'CR AND S',
            'CZ',
            'DAELIM',
            'DERBI',
            'DKW',
            'DNEPR',
            'DODGE',
            'DOLMER',
            'DOUGLAS',
            'DUCATI',
            'EBR',
            'ESCORTS',
            'EXCELSIOR',
            'FANTIC',
            'FERRARI',
            'FISCHER',
            'FLYSCOOTERS',
            'FUTONG',
            'GARELLI',
            'GAS GAS',
            'GENERIC',
            'GENEVA',
            'GILERA',
            'HDT',
            'HERCULES',
            'HERO HONDA',
            'HIGHLAND',
            'HONDA',
            'HOREX',
            'HUSABERG',
            'HUSQVARNA',
            'HYOSUNG',
            'ICON',
            'IDEAL JAWA',
            'INDIAN',
            'ITALJET',
            'JAMES',
            'JAWA',
            'JINLANG',
            'JRL',
            'KAWASAKI',
            'KEEWAY',
            'KREIDLER',
            'KTM',
            'KYMCO',
            'LAVERDA',
            'LITO',
            'MAHINDRA',
            'MAICO',
            'MALAGUTI',
            'MANSORY',
            'MATCHLESS',
            'MBK',
            'MINI',
            'MINSK',
            'MISSION MOTORS',
            'MITSUBISHI MOTORS',
            'MODENAS',
            'MONDIAL',
            'MOTESA',
            'MORINI',
            'MOTO FGR',
            'MOTO GUZZI',
            'MOTO MORINI',
            'MOTO CZYSZ',
            'MOTO LEVO',
            'MOTORHISPANIA',
            'MOTUS',
            'MTT',
            'MUNCH',
            'MUZ',
            'MV AUGUSTA',
            'MZ',
            'NCR',
            'NEANDER',
            'NEMBO MOTOCICLETTE',
            'NORTON',
            'NSU',
            'ORION',
            'OSSA',
            'PANNONIA',
            'PANTHER',
            'PETRONAS',
            'PEUGEOT',
            'PGO SCOOTERS',
            'PIAGGIO',
            'POLARIS',
            'PUCH',
            'QUADRO',
            'RADIAL ENGINE',
            'REGENT',
            'RENARD',
            'RIEJU',
            'ROEHR',
            'ROKON',
            'ROTAX',
            'ROYAL ENFIELD',
            'SACHS',
            'SBAY',
            'SCOTT',
            'SHERCO',
            'SHL',
            'SIEMENS',
            'SIMSON',
            'SMART',
            'SOKOL',
            'SUNBEAM',
            'SUZUKI',
            'SYM',
            'TRACK',
            'TRIUMPH',
            'TROJAN',
            'TUNTURI',
            'TVS',
            'URAL',
            'VAHRENKAMP',
            'VECTRIX',
            'VELOCETTE',
            'VERTEMATI',
            'VESPA',
            'VICTORY',
            'VINCENT',
            'VOLTA',
            'VOR',
            'VOXAN',
            'VYRUS',
            'WALZ HARDCORE CYCLES',
            'WEST COAST CHOPPERS',
            'YAMAHA',
            'YUMBO',
            'ZERO',
            'ZONGSHEN',
            'ZUNDAPP'
        );

        return $motorcycles;
    }
}